version: '3.8'

services:
  cryptoportfolio-django:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - ${PORT}:8000
    env_file:
      - .env
      - .env.production
    volumes:
      - ./:/cryptoportfolio-django
    restart: always
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: ${PG_DB}
volumes:
  db:
