# Generated by Django 4.0.1 on 2022-03-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=19, max_digits=65)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriceAnalysis.asset')),
            ],
        ),
    ]
