# Generated by Django 4.0.1 on 2022-03-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAnalysis', '0002_holding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='last_price',
        ),
    ]
