# Generated by Django 4.0.4 on 2022-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAnalysis', '0004_price_pricechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
                ('sender_mail', models.CharField(max_length=64)),
            ],
        ),
    ]
